### ISSUE TITLE
NumberFormatException for a Column of type integer (nullable = true)

### ISSUE THREAD

**Issue by dkirrane** [databricks/spark-csv#239]
I'm using an inferred schema. Any time I add a column that has type `integer (nullable = true)`
I get

```
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:53)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:181)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:162)
```

**Comment by falaki** [comment]
Can you verify if there is no space or other characters before or after the delimiter?

**Comment by dkirrane** [comment]
Ya I found a couple of `n/a` in that column. It would be good if instead of the NFE to instead log a warning and print the invalid cells value.

**Comment by falaki** [comment]
That's what spark-csv does.

**Comment by nightscape** [comment]
I have a similar problem, where the data looks like this
```
a
1
""
2
""
```
So in my case, empty quotes should be transformed to a `null` value (column `a` is configured as `nullable`), but instead a `NumberFormatException` is thrown.
Setting `option("nullValue", "\"\"")` also does not  work.
Is this expected? If so, is there a workaround?

Thanks!

**Comment by HyukjinKwon** [comment]
@dkirrane @nightscape Could you provide the codes and data so that I can reproduce and fix this?

**Comment by nightscape** [comment]
Oh, I had tried this from a git checkout of Spark (which already says 2.0.0).
I checked again under Spark 1.6.1 and there it worked as expected.
Do you need the code to replicate this behavior under the current Spark version, or would you rather wait until 2.0 final is released?

**Comment by HyukjinKwon** [comment]
@nightscape Good to know that! I think it is fine because then it means an issue in Spark not in this library and it is fixed already. Let me check out if there are related issues in JIRA.

**Comment by Azuaron** [comment]
I'm having this problem in Scala 2.10.5, Spark 1.6.1, spark-csv 1.4.0. If an integer value is set to `nullable = false` and a null value is present, it throws a NumberFormatException instead of an NPE or (even better) a descriptive message about the column and row. And, since I'm using PERMISSIVE mode, I would really expect to fail that row but continue processing the rest of the file.

```scala
private val proficiencyStruct = StructType(Array(
				StructField(academicYear, StringType, false),
				StructField(stateTest, StringType, false),
				StructField(season, StringType, false),
				StructField(subject, StringType, false),
				StructField(grade, StringType, false),
				StructField(score, IntegerType, true),
				StructField(level1, IntegerType, true),
				StructField(level2, IntegerType, true),
				StructField(level3, IntegerType, true),
				StructField(level4, IntegerType, true),
				StructField(level5, IntegerType, true),
				StructField(prof, IntegerType, true)
		));
```

In the above, I had to modify most of the IntegerType columns to be `nullable = true` and perform my own null checking later (some of them really are nullable).

```
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:61)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:120)
        at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:106)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:148)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

IMO, the problem smells like it's not converting empty Strings to nulls when nulls are rejected until after it tries (and fails) to convert to an Integer.

**Comment by anupash147** [comment]
Ouuch.. I hit this one.. what is the temporary work around??

**Comment by Azuaron** [comment]
I set nullable = false and performed my own validation.

**Comment by Venkateshgovind** [comment]
The problem still exists in 2.0.1

val dataFrame = spark.read
						    .schema(customSchema)
						    .option("header", "false") 
						    .option("inferSchema", "false") 
						    .option("escape", "\\")
						    .option("encoding", "Windows-1252")
						    .option("nullValue", "")
						    .csv(csvHdfsUri)

Looks like the option nullValue has no effect for empty string.

My data looks like this:
"","6","BMW"
"","","Gm"

If I were to change my data to 
"","6","BMW"
"","null","Gm"

then the above code works (with .option("nullValue", "null"))

Custom Schema is as follows: (The 1 and 0 denote whether a field is nullable)
DummyCol,StringType,1
IntegerCol,IntegerType,1
Name,StringType,0


Any thoughts?

**Comment by HyukjinKwon** [comment]
Hm, have you tried quote related options?

**Comment by Venkateshgovind** [comment]
With regards to quote option, I can see that I am already using the default character which is a double quote to encapsulate the values in the csv file. Is there a specific option that you are referring to? Thanks for taking  a look.

**Comment by HyukjinKwon** [comment]
Ah, I see. Let me try to reproduce this case first. Thanks.

**Comment by Venkateshgovind** [comment]
I changed my data file to not enclose non string types in quotes like this and got it to work.
"",6,"BMW"
"",,"Gm"

**Comment by SargisPlusPlus** [comment]
Ah, I hit this issue as well... Seems like it is coming from: https://github.com/databricks/spark-csv/blob/master/src/main/scala/com/databricks/spark/csv/util/TypeCast.scala#L57
I am new to Spark and Scala, but would wrapping datum.toInt with a Try(datum.toInt).getOrElse(null) work? 
I tried building jar to test it but I can't since CSV is baked in Spark 2.0.0 so I am hitting "Multiple sources found for csv".

**Comment by Brajen259** [comment]
I am having the same issue too in spark 2.0.0 dataframes(pyspark). I also used .option('nullValue','null') but seems like no impact.
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$.castTo(CSVInferSchema.scala:244)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:115)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:84)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$1.apply(CSVFileFormat.scala:125)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$1.apply(CSVFileFormat.scala:124)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:128)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

Any suggestions

**Comment by Alucard4635** [comment]
The primary way of interacting with null values, at DataFrame scale, is to use the .na subpackage
on a DataFrame.
you can:
Drop:
Passing in “any” as an argument will drop a row if any of the values are null.
Passing in “all” will only drop the row if all values are null or NaN for that
row. df.na.drop("all")
or fill:
df.na.fill("All Null values become this string")
or you can replace them:
df.na.replace("colName", Map("" -> "UNKNOWN"))
