### ISSUE TITLE
character corruption when spark.executor.memory is not set to a proper value

### ISSUE THREAD

**Issue by DarkForte** [databricks/spark-csv#285]
Hi, I noticed a strange bug recently.

Here is my sample code:

```
object sparktry
  {
    def main(args: Array[String])
    {
      AutoLogger.setLevel("INFO")
  
      val sc = SingletonSparkContext.getInstance()
      val sql_context = SingletonSQLContext.getInstance(sc)
  
      val options = new collection.mutable.HashMap[String, String]()
      options += "header" -> "true"
      options += "charset" -> "UTF-8"
  
      val customSchema = StructType(Array(
        StructField("Year", StringType),
        StructField("Brand", StringType),
        StructField("Category", StringType),
        StructField("Model", StringType),
        StructField("Sales", DoubleType)))
  
      val dataFrame = sql_context.read.format("com.databricks.spark.csv")
      .options(options)
      .schema(customSchema)
      .load("hdfs://myHDFSserver:9000/BigData/CarSales.csv")
  
      dataFrame.head(10).foreach(x => AutoLogger.info(x.toString))
    }
  }
```

CarSales is a very small csv. I noticed that when `spark.master` is not `local`, setting `spark.executor.memory` to above 16GB will result in the corruption of DataFrame. The output of this program is shown as below: (I copied the text from the log, and in this case `spark.executor.memory` is set to 32GB)
 
```
16/03/07 12:39:50.190 INFO DAGScheduler: Job 1 finished: head at sparktry.scala:35, took 8.009183 s
16/03/07 12:39:50.225 INFO AutoLogger$: [       ,  ,      ,ries       ,142490.0]
16/03/07 12:39:50.225 INFO AutoLogger$: [       ,  ,      ,ries       ,112464.0]
16/03/07 12:39:50.226 INFO AutoLogger$: [       ,  ,      ,ries       ,90960.0]
16/03/07 12:39:50.226 INFO AutoLogger$: [       ,  ,      ,ries       ,100910.0]
16/03/07 12:39:50.226 INFO AutoLogger$: [       ,  ,      ,ries       ,94371.0]
16/03/07 12:39:50.226 INFO AutoLogger$: [       ,  ,      ,ries       ,54142.0]
16/03/07 12:39:50.226 INFO AutoLogger$: [       ,  ,       ,ries       ,14773.0]
16/03/07 12:39:50.226 INFO AutoLogger$: [       ,  ,       ,ries       ,12276.0]
16/03/07 12:39:50.227 INFO AutoLogger$: [       ,  ,       ,ries       ,9254.0]
16/03/07 12:39:50.227 INFO AutoLogger$: [       ,  ,       ,ries       ,12253.0]
```

While the first 10 lines of the file is:

```
1/1/2007,BMW,Compact,BMW 3-Series,142490.00
1/1/2008,BMW,Compact,BMW 3-Series,112464.00
1/1/2009,BMW,Compact,BMW 3-Series,90960.00
1/1/2010,BMW,Compact,BMW 3-Series,100910.00
1/1/2011,BMW,Compact,BMW 3-Series,94371.00
1/1/2007,BMW,Compact,BMW 5-Series,54142.00
1/1/2007,BMW,Fullsize,BMW 7-Series,14773.00
1/1/2008,BMW,Fullsize,BMW 7-Series,12276.00
1/1/2009,BMW,Fullsize,BMW 7-Series,9254.00
1/1/2010,BMW,Fullsize,BMW 7-Series,12253.00
```

I noticed that by only changing `spark.executor.memory` to 16GB on my machine, the first 10 lines is correct, but setting it to over 16GB will result in the corruption.

What's more: On one of my servers which have 256GB's memory, setting this to 16GB also produces this bug. Instead, setting it to 48GB will make it work fine. In addition, I tried to print `dataFrame.rdd`, it shows that the content of RDD is correct, while the dataframe itself is not.

Does anyone have any idea about this problem?

Thank you!

**Comment by davies** [comment]
What's the version of Spark are you using? This should be fixed in master, I think.

**Comment by DarkForte** [comment]
@davies I'm using Spark 1.5.1.

Please hold on to this issue, as I found this might be an issue in Spark, not in this library. I'll keep updating about this issue if I have any progress.

Thank you!

**Comment by HyukjinKwon** [comment]
Yea, I have been also thinking this might be related with https://github.com/databricks/spark-csv/issues/231 or an issue at Spark.

So, this test  is being failed right?

```scala
assert(dataFrame.rdd.collect() === dataFrame.collect())
```

**Comment by DarkForte** [comment]
@HyukjinKwon Yes, `dataFrame.rdd` is correct.

In fact, it turns out this is a bug of Spark 1.5.1, for I've written the following code to exclude Spark-csv:

```
object sparktry
{
  def main(args: Array[String])
  {
    AutoLogger.setLevel("INFO")

    val sc = SingletonSparkContext.getInstance()
    val sql_context = SingletonSQLContext.getInstance(sc)

    val path = "hdfs://myHDFSServer:9000/BigData/CarSales.csv"

    val customSchema = StructType(Array(
      StructField("Year", StringType),
      StructField("Brand", StringType),
      StructField("Category", StringType),
      StructField("Model", StringType),
      StructField("Sales", StringType)))

    val textRDD = sc.textFile(path)

    val seqRDD = textRDD.map(x =>x.split(",").toSeq)

    val rowRDD = seqRDD.map(x => Row.fromSeq(x))

    val dataFrame = sql_context.createDataFrame(rowRDD, customSchema)

    dataFrame.show()
  }
}
```

I found that it still encounters bad encoding. However, when I switch to Spark 1.3.1 and Spark 1.6.0, neither gives the same bug under exactly the same configuration.

I checked Spark's issue list but find no related issues. Did they by chance fixed 

Above all, it turns out that spark-csv is not the one to blame for this bug. Sorry to bother you!

**Comment by davies** [comment]
https://issues.apache.org/jira/browse/SPARK-11737?jql=project%20%3D%20SPARK%20AND%20text%20~%20%22string%20kyro%22

**Comment by davies** [comment]
It's fixed in 1.5.3 (not released) and 1.6.0

**Comment by HyukjinKwon** [comment]
Cool, then can we maybe close this?

**Comment by DarkForte** [comment]
@davies Thank you for the related resource. I'll close this issue.
