### ISSUE TITLE
how to write "DATE" data type in spark-csv

### ISSUE THREAD

**Issue by engrsriram** [databricks/spark-csv#392]
i have data similar to this. 

```
    no,full_name,Ocupation,DOB
    1,Eugene Perry,Physical Therapy Assistant,11/22/1972
    2,Scott Evans,Account Executive,8/25/1961
    3,Harold Porter,Community Outreach Specialist,4/5/1986
    4,Roger Turner,Account Coordinator,12/24/1989
    5,Patrick Freeman,Geological Engineer,2/11/1990
    6,Jonathan Hart,Safety Technician I,7/24/1963
    7,Susan Jenkins,Nurse,4/17/1967
    8,Jason Graham,Internal Auditor,10/18/1966
    9,Mark Wells,VP Marketing,2/20/1990

```

My Code Similar to this:(Java)

 

```
     SparkSession spark = SparkSession
                    .builder()
                    .appName("Java Spark SQL Example")
                    .config("spark.some.config.option", "some-value")
                    .config("spark.sql.warehouse.dir", "file:///C:/tmp/") 
                    .getOrCreate();
           
           StructType Const = new StructType(new StructField[] {
       		    new StructField("no", DataTypes.IntegerType, true, Metadata.empty()),
       		    new StructField("full_name", DataTypes.StringType, true, Metadata.empty()),
       		    new StructField("Ocupation", DataTypes.StringType, true, Metadata.empty()),
       		    new StructField("DOB", DataTypes.DateType, true, Metadata.empty())
       		});
    				Dataset<Row> Tem  =  spark.read().format("com.databricks.spark.csv")
    						.schema(Const).option("header", "true").option("delimiter", ",").option("dateFormat", "MM/DD/YYYY")
    						.load("E:\\Datasets\\people.csv");
    		
    				Tem.show();
    				Tem.printSchema();
    				Tem.coalesce(1).write()
    			        .format("com.databricks.spark.csv")
    			        .option("header", "true").option("dateFormat", "MM/DD/YYYY")
    			        .save("E:\\Datasets\\output");
```

Above code works fine without errors,but DATE datatype( "DOB" )column is not properly printed in flat file. 

my Actual result is :

```
    no,full_name,Ocupation,DOB
    1,Eugene Perry,Physical Therapy Assistant,724
    2,Scott Evans,Account Executive,-3287
    3,Harold Porter,Community Outreach Specialist,5841
    4,Roger Turner,Account Coordinator,6940
    5,Patrick Freeman,Geological Engineer,7304
    6,Jonathan Hart,Safety Technician I,-2559
```

even though i am using `.option("dateFormat", "MM/DD/YYYY")` .  in last column , "DATE" formatting isn't working in .csv file. 
i am not sure what i am missing.

**Comment by falaki** [comment]
What version of spark-csv are you using? What is your spark version?

**Comment by engrsriram** [comment]
spark-csv_2.10 version 1.5.0.

Just for Reference, i am using this one in my pom.xml file. 

````
<!-- Import Spark -->`
        <dependency>
    		<groupId>org.apache.spark</groupId>
    		<artifactId>spark-sql_2.10</artifactId>
    		<version>2.0.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.databricks/spark-csv_2.10 -->
		<dependency>
    		<groupId>com.databricks</groupId>
    		<artifactId>spark-csv_2.10</artifactId>
    		<version>1.5.0</version>
		</dependency>
```

**Comment by kyrozetera** [comment]
I'm seeing this same issue. The source date in my file is in the format `yyyy-MM-dd`. For example "2016-11-08" writes out to "17086" in the output file. Tested with both spark-csv version 1.4.0 and 1.5.0 on spark 2.0.0 and get the same result.

Upgrading to spark 2.0.1 and using the built-in spark CSV format fixes the issue.

**Comment by HyukjinKwon** [comment]
Have you guys checked `Locale.getDefault()`? Parsing decimals and dates is varied by this. From 2.1, it was fixed as `Locale.US`. Maybe, we should be able to set this.

**Comment by kyrozetera** [comment]
`Locale.getDefault()` returns `en_US` for spark 2.0.0 and 2.0.1. On spark 2.0.1,  using spark-csv 1.5.0, the date gets formatted correctly. So it appears to just be an issue with spark 2.0.0.

**Comment by falaki** [comment]
@kyrozetera note that you don't need to and should not use spark-csv package with spark 2.x

**Comment by kyrozetera** [comment]
@falaki I found that out recently since we just started using spark 2.0.0 in our stack, so we're switching to the built-in CSV format. But I was trying to isolate the issue for the OP since he is also on 2.0.0. This issue persists in 2.0.0 whether using the spark-csv package or not. The fix is being back-ported I believe, but we have upgraded to spark 2.0.1 and the issue is solved.

**Comment by engrsriram** [comment]
yes. this issue is no more in spark 2.0.1 version
